import type { MigrationConfig } from "../types";

/**
 * A worked example config, grounded in brightframe's own README ("Origin" section):
 * the exact adaptations made when these components were extracted from lan-site's
 * internal, pre-extraction component library into the public `brightframe` package.
 *
 * This is an *example* to copy and adjust for your own legacy kit, not a config
 * meant to be run against lan-site's real app code today — lan-site itself already
 * migrated (see `reports/lan-site-dry-run.md`, generated by dry-running this exact
 * config against lan-site's now-dead pre-extraction component directory).
 */
const lanSiteExampleConfig: MigrationConfig = {
  packageName: "brightframe",
  rules: [
    // Safe: converted to CSS Modules during extraction, but no prop/behavior changes —
    // a straight default-import → named-import rewrite is enough.
    { legacyName: "Title", brightframeName: "Title", kind: "safe-rename" },
    { legacyName: "SubTitle", brightframeName: "SubTitle", kind: "safe-rename" },
    { legacyName: "Link", brightframeName: "Link", kind: "safe-rename" },
    { legacyName: "Container", brightframeName: "Container", kind: "safe-rename" },
    { legacyName: "Burger", brightframeName: "Burger", kind: "safe-rename" },
    { legacyName: "Loader", brightframeName: "Loader", kind: "safe-rename" },

    // Manual review: the legacy `Button` takes a `to: string` prop and calls
    // `useRouter().push(to)` itself (a next/navigation dependency brightframe's `Btn`
    // deliberately doesn't have — routing is left to the consumer via `href`/`onClick`,
    // per the README's "Origin" section). Auto-rewriting this would silently drop
    // real navigation behavior, so it's flagged instead of rewritten.
    {
      legacyName: "Button",
      brightframeName: "Btn",
      kind: "manual-review",
      note: 'Legacy `Button` navigates internally via `useRouter().push(to)`; `Btn` has no routing of its own. Replace with `<Btn onClick={() => router.push(to)}>` (or an `href`, if `to` is a plain URL) and drop the `to` prop.',
    },
  ],
};

export default lanSiteExampleConfig;
